project_id = "nltggocnysiewnbmqfrj"

[functions.scan-x-profile]
verify_jwt = false

[functions.resolve-arena-battle]
verify_jwt = false

[functions.validate-x-post]
verify_jwt = false

[functions.admin-user-snapshot]
verify_jwt = false

[functions.verify-recaptcha]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
